# -*- coding: utf-8 -*-
"""BAN3110 Week 3 Module 3 HW3 Omy Ortiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjkRTdd9_PNy-uL7Q4ZrViaV0stWwYac

**BAN3110** Module 3 Homework 3
#####**Name:** Omy Ortiz
#####**AI Use Statement:** I used ChatGPT to explain my method and approach, help with Google Colab, and get help with Python syntax.  I typed, ran, and checked all of the code.

##### **Problem 1**: Write program with while loop which finds the followings for the given values between 150 to 1000.
#####a) How many odd numbers are between 150 and 1000 (include 150 and 1000)
#####b) Find the sum of odd numbers which are between 150 and 1000 (include 150 and 1000)
#####c) Find the multiplication of odd numbers which are between 150 and 1000 (include 150 and 1000)
#####d) Find the sum of square of odd numbers which are between 150 and 1000 (include 150 and 1000)
"""

number = 150
count_odd = 0
sum_odd = 0
product_odd = 1
sum_squares_odd = 0

while number <= 1000:
  if number % 2 !=0:
    count_odd += 1
    sum_odd += number
    product_odd *= number
    sum_squares_odd += number**2
  number += 1

print("Count of odd numbers:", count_odd)
print("Sum of odd numbers:", sum_odd)
print("Product of odd numbers:", product_odd)
print("Sum of squares of odd numbers:", sum_squares_odd)

"""##### **Problem 2**: Write program with for loop which finds the followings for the given values between 150 to 1000.
#####a) How many odd numbers are between 150 and 1000 (include 150 and 1000)
#####b) Find the sum of odd numbers which are between 150 and 1000 (include 150 and 1000)
#####c) Find the multiplication of odd numbers which are between 150 and 1000 (include 150 and 1000)
#####d) Find the sum of square of odd numbers which are between 150 and 1000 (include 150 and 1000)
"""

count_odd = 0
sum_odd = 0
product_odd = 1
sum_squares_odd = 0

for number in range(150, 1001):
    if number % 2 != 0:
        count_odd += 1
        sum_odd += number
        product_odd *= number
        sum_squares_odd += number**2

print("Count of odd numbers:", count_odd)
print("Sum of odd numbers:", sum_odd)
print("Product of odd numbers:", product_odd)
print("Sum of squares of odd numbers:", sum_squares_odd)

"""##### **Problem 3**: Write a program so that for given M."""

M = int(input("Enter a value for M: "))

number = 1
summation = 0

while number <= M:
    summation += number
    number += 1

print("The result of the summation is:", summation)

"""##### **Problem 4**: Write a program which repeatedly reads numbers until the user enters “done”. Once “done” is entered, print out the total, count, and average of the numbers. If the user enters anything other than a number, detect their mistake using try and except and print an error message and skip to the next number."""

total = 0
count = 0

while True:
    user_input = input("Enter a number (or type 'done' to finish): ")

    if user_input == "done":
        break

    try:
      number = float(user_input)
      total += number
      count += 1
    except:
      print("Invalid input. Please enter a number.")

if count > 0:
    average = total / count
    print("Total:", total)
    print("Count:", count)
    print("Average:", average)
else:
  print("No valid numbers were entered.")

"""##### **Problem 5**: Write another program that prompts for a list of numbers as above (question 4) and at the end prints out both the maximum and minimum of the numbers instead of the average."""

total = 0
count = 0
maximum = None
minimum = None

while True:
    user_input = input("Enter a number (or type 'done' to finish): ")

    if user_input == "done":
        break

    try:
        number = float(user_input)
        total += number
        count += 1

        if maximum is None or number > maximum:
            maximum = number

        if minimum is None or number < minimum:
            minimum = number

    except:
        print("Invalid input. Please enter a number.")

if count > 0:
      print("Total:", total)
      print("Count:", count)
      print("Maximum:", maximum)
      print("Minimum:", minimum)
else:
      print("No valid numbers were entered.")

"""##### **Problem 6**: What is printed by the Python code?
for z in [2, 4, 7, 9]:
#####print(z – 1)
"""

for z in (2, 4, 7, 9):
    print(z-1)

"""##### **Problem 7**: What is printed by the Python code?
n = 3
#####for x in [2, 5, 8]:
n = n + x
#####print n
"""

n = 3
for x in [2, 5, 8]:
  n = n + x
print(n)